const test=require('node:test');
const assert=require('node:assert/strict');
const core=require('../web/ab-strategies.js');
function bars(n=250){return Array.from({length:n},(_,i)=>{const close=100+0.08*i+3*Math.sin(i/4); return {date:new Date(Date.UTC(2025,0,i+1)).toISOString().slice(0,10),open:close-0.3,high:close+1,low:close-1,close,volume:5000+(i%9)*250,foreign:(i%2?15:-10),trust:20};});}
test('compute does not mutate input and returns chronological histogram',()=>{const b=bars();const orig=JSON.stringify(b);const x=core.compute(b);assert.equal(x.bars.length,b.length);assert.equal(x.hist.length,b.length);assert.equal(JSON.stringify(b),orig);assert.equal(x.bars[0].date,'2025-01-01');});
test('A original signal is not affected by B-only filters',()=>{const x=core.compute(bars());for(let i=41;i<x.bars.length;i++){const a=core.signalAt(x,i,1,'A');const b=core.signalAt(x,i,1,'B',{volumeRatio:10});assert.ok(!b.pass||a.pass);} });
test('signal at historical i cannot inspect later prices',()=>{const b=bars();const x=core.compute(b);const before=core.signalAt(x,120,1,'A');for(let i=121;i<b.length;i++){b[i].close+=100;b[i].high+=100;b[i].low+=100;b[i].open+=100;}const after=core.signalAt(core.compute(b),120,1,'A');assert.deepEqual(before,after);});
test('no fake profit from unchanged fill prices with costs',()=>{const b=bars(100).map(x=>({...x,open:100,high:101,low:99,close:100}));const r=core.backtest(b,'A');assert.equal(r.count,0);assert.equal(r.markedReturn,0);});
test('A and B backtests share same data and costs, B never exceeds A entry count',()=>{const b=bars(260),a=core.backtest(b,'A'),c=core.backtest(b,'B',{volumeRatio:1.5});assert.equal(a.bars,c.bars);assert.ok(c.count<=a.count);assert.ok(a.curve.every(p=>Number.isFinite(p.equity)));assert.ok(c.curve.every(p=>Number.isFinite(p.equity)));});
test('closed trades fill strictly after signal timestamp, and no lookahead extreme prices',()=>{const b=bars(350),r=core.backtest(b,'A');assert.ok(r.trades.length>0,'synthetic market should create trades');for(const t of r.trades){assert.ok(t.signal<t.entryDate);assert.ok(t.entryDate<t.exitDate);const ent=b.find(x=>x.date===t.entryDate);assert.equal(t.entryPrice,ent.open);}});
test('Fugle historical 60 format imports and sorts',()=>{const b=bars(80),data=core.parseFugleHistorical({timeframe:'60',data:[...b].reverse()});assert.equal(data[0].date,b[0].date);assert.equal(data.length,80);});
test('Invalid price data and mismatched timeframe are rejected',()=>{assert.throws(()=>core.compute([{date:'2025-01-01',open:100,high:99,low:98,close:100,volume:10}]));assert.throws(()=>core.parseFugleHistorical({timeframe:'D',data:bars()}));});
